### ISSUE TITLE
Missing css variables in themes

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-theming#55]
## Description  
In fluent themes the css variables `--ig-info-*`, `--ig-success-*`, `--ig-warn-*` and `--ig-error-*` are missing.

 * igniteui-angular version: 15.0.0

## Result  
For example invalid inputs are not red anymore.

**Comment by SisIvanova** [comment]
Hi @Timmeeeey,
 If you're using one of the Ignite UI theme presets like the `fluent-light-theme()`, then your issue should be fixed with this PR - IgniteUI/igniteui-angular/pull/12382
 Otherwise, if you're creating a custom palette you should provide values for the `info`, `success`, `warn`, and `error` colors. You can check this sample for further information about how to use colors from our predefined color palettes:
 https://stackblitz.com/edit/angular-uskfyf?file=src/styles.scss

**Comment by Timmeeeey** [comment]
Hi @SisIvanova 
Actually I'm importing the preset `node_modules/@infragistics/igniteui-angular/styles/igniteui-fluent-light-word.css`.

**Comment by SisIvanova** [comment]
> Hi @SisIvanova Actually I'm importing the preset `node_modules/@infragistics/igniteui-angular/styles/igniteui-fluent-light-word.css`.

Then the aforementioned PR will fix the problem.
